### ISSUE TITLE
404 Not Found tootallnate%2fonce  from version 4.0.1

### ISSUE THREAD

**Issue by jaganathan** [TooTallNate/node-http-proxy-agent#16]
npm ERR! code E404
npm ERR! 404 Not Found - GET http://*****/@tootallnate%2fonce - no such package available
npm ERR! 404
npm ERR! 404  '@tootallnate/once@1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'http-proxy-agent'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\build1\build_dca\rbuild\.npm\_logs\2020-02-13T08_53_45_450Z-debug.log

**Comment by TooTallNate** [comment]
This was probably a caching issue. [The package is indeed public](https://www.npmjs.com/package/@tootallnate/once).
