### ISSUE TITLE
Exported API does not match README

### ISSUE THREAD

**Issue by otakustay** [TooTallNate/node-http-proxy-agent#17]
In README this library is used as a class:

```js
import ProxyAgent from 'http-proxy-agent';

new ProxyAgent(options);
```

In typescript definition the export is a function:

```js
import createHttpProxyAgent from 'http-proxy-agent';

createHttpProxyAgent(options);
```

**Comment by TooTallNate** [comment]
You are correct, however there is a [backwards-compatibility shim](https://github.com/TooTallNate/node-http-proxy-agent/blob/cab60b0a678dbf80648fa0650ac68525efc5b26e/src/index.ts#L34) such that the old-style JS code still works as expected (that is, you can use `new` keyword, and `instanceof` works correctly).

For modern TypeScript code I would recommend to use the factory function:

```typescript
import createHttpProxyAgent from 'http-proxy-agent';

createHttpProxyAgent(options);
```

_Or_ import the `HttpProxyAgent` class directly:

```typescript
import { HttpProxyAgent } from 'http-proxy-agent';

new HttpProxyAgent(options);
```

Hope that helps!

**Comment by otakustay** [comment]
I suggest update README to `createHttpProxyAgent` to reduce user confusion in the future :)
