### ISSUE TITLE
Please release new module to remove self-signed certs in pacakge from agent-base

### ISSUE THREAD

**Issue by Javaman2** [TooTallNate/node-http-proxy-agent#18]
https://github.com/TooTallNate/node-http-proxy-agent/tree/master/test

**Comment by TooTallNate** [comment]
What version are you using? The `test` dir is already not bundled in the npm package as of `v4.0.0` and newer.

**Comment by Javaman2** [comment]
The version 2.1 was deep into the dependency list, none of which I was using in my lib.  I did an npm uninstall and reinstall  and now the version is showing 4.01.  But NPM version 6.15 has the old dependencies included.  Let me see if I can fix NPM.

**Comment by Javaman2** [comment]
I upgraded Angular to Version 10.0.0, these errors disappeared! Thanks for help.

**Comment by Javaman2** [comment]
Angular 10 upgrade fixed these errors.
