### ISSUE TITLE
Http(s)ProxyAgent is not compatible with node 14 Agent

### ISSUE THREAD

**Issue by marikaner** [TooTallNate/node-http-proxy-agent#19]
Using the Http(s)ProxyAgent fails with the following error.

```sh
error TS2741: Property 'freeSockets' is missing in type 'HttpsProxyAgent' but required in type 'Agent'
```

This is due to the fact that the Http(s)ProxyAgent extends a custom Agent, that is not based on the node `http.Agent`.

**Comment by TooTallNate** [comment]
Please run `yarn upgrade` / `npm update`, you want `agent-base@6.0.2` or newer.
