### ISSUE TITLE
Node 14: Not work in Termux (Mobile network 4G) ... with WiFi work ok.

### ISSUE THREAD

**Issue by ruslanx3m** [TooTallNate/node-http-proxy-agent#20]
**Node 14**: Not work in Termux (Mobile network **4G**) ... with **WiFi** work ok.

without node-http-proxy-agent - work in both.

_(node-fetch, axios tested)_

for https - version.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
