### ISSUE TITLE
Property 'maxTotalSockets' is missing in type 'HttpProxyAgent' but required in type 'Agent'.

### ISSUE THREAD

**Issue by marikaner** [TooTallNate/node-http-proxy-agent#21]
I get this error with `@types/node` version `12.19.2`.

**Comment by marikaner** [comment]
This is similar to https://github.com/TooTallNate/node-http-proxy-agent/issues/19

**Comment by TooTallNate** [comment]
Please run `yarn upgrade` / `npm update`, you want `agent-base@6.0.2` or newer.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
