### ISSUE TITLE
Stuck when pipe or request.write()

### ISSUE THREAD

**Issue by Fosper** [TooTallNate/node-http-proxy-agent#22]
const fs = require('fs');
const url = require('url');
const https = require('https');
const HttpProxyAgent = require('http-proxy-agent');

let requestOptions = url.parse('https://127.0.0.1');

requestOptions.method = 'POST';
requestOptions.agent = new HttpProxyAgent('http://127.0.0.1:3000'); // <--- If comment this - all works fine.

let request = https.request(requestOption, (res) => {
res.pipe(process.stdout);
});

fs.createReadStream(__dirname + '/test.txt').pipe(request); // <--- Didn't work. request.write('Hello') didn't work too. Just stuck.

// Working only request.end('Hello'), but sometimes i need send files and use Readable streams.
// p.s. socks-proxy-agent working very fine with request.write('Hello') and .pipe(request).
// p.s.s. 127.0.0.1 - just for example.

**Comment by TooTallNate** [comment]
This code in this repository has been moved to the [`proxy-agents` monorepo](https://github.com/TooTallNate/proxy-agents), so I am closing this pull request. If you feel that this issue still exists as of the latest release, feel free to open a new issue over there.
