### ISSUE TITLE
{ error: [Error: Hostname/IP doesn't match certificate's altnames] }

### ISSUE THREAD

**Issue by vinnitu** [TooTallNate/node-http-proxy-agent#5]
I have got this error when trying to connect to own https server with self-signed server.
How to disable certificate check?

**Comment by TooTallNate** [comment]
You have to set `rejectUnauthorized: true` on the proxy opts object. See like how the tests do it: https://github.com/TooTallNate/node-http-proxy-agent/blob/ee0beb4497a6a89bca314ad77929fe204692f21c/test/test.js#L142-L145
