### ISSUE TITLE
connect ETIMEDOUT

### ISSUE THREAD

**Issue by thisKeeWord** [TooTallNate/node-http-proxy-agent#6]
i copied and pasted the example code into my server file and I still cannot figure out why i'm getting a connect timeout issue.

**Comment by TooTallNate** [comment]
The proxy IP in that example is not a real IP address. You'll need to set up your own proxy server and point the HttpProxyAgent instance to that proxy's address.

**Comment by thisKeeWord** [comment]
How do i set up my proxy server? (i've been looking up ways, but i've only ended up at square 1)
I could greatly use your help.

**Comment by TooTallNate** [comment]
Are you sure you actually need a proxy server at all? What's your use-case?

**Comment by thisKeeWord** [comment]
The goal would be to route specific network requests live without the need for browser-mob-proxy and browserstack (or the like)
